spring:
  datasource:
    url:  jdbc:oracle:thin:@localhost:1521:xe
    username: toribro
    password: 1234
    driver-class-name: oracle.jdbc.driver.OracleDriver

  jpa:
    hibernate:
      ddl-auto:
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers:
        generate_statistics:
        id:
          new_generator_mappings:

  mvc:
    hidden-method:
      filter:
        enabled: true

mybatis:
  type-aliases-package: com.toribro.space.domain.entity
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml



logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace


#logging.level.hello.itemservice.repository.mybatis=trace